FROM golang:1.16.2

ENV GOLANG_CI_LINT_VERSION=v1.18.0

RUN cd /usr && \
    wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s ${GOLANG_CI_LINT_VERSION}

WORKDIR /app
